name: Free VLESS Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Download binary
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.9.0/sing-box-1.9.0-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          mv sing-box-*/sing-box sing-box
      - name: Start VLESS Server
        run: |
          sudo apt update
          chmod +x sing-box
          ./sing-box run -c <(curl -s https://raw.githubusercontent.com/XTLS/Xray-install/main/Reality/vless-grpc.json)
      - name: Keep alive
        run: |
          while true; do echo "Running..."; sleep 300; done

